JavaScript
window.generatePlan = async function() {
    const input = document.getElementById('youtubeInput').value;
    const btn = document.getElementById('btn');
    const container = document.getElementById('resultContainer');
    const section = document.getElementById('resultSection');

    if (!input) return alert("분석할 정보를 입력해주세요!");

    btn.disabled = true;
    btn.innerText = "양식에 맞춰 기획안 생성 중...";

    // 💡 1. 여기에 발급받은 Gemini API 키를 넣으세요.
    const API_KEY = "AIzaSyAAtwzmXk5bwuQI8lTuCsTwSMGLy0ElQJw";
    const URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${API_KEY}`;

    try {
        // 💡 2. Gemini API 규격에 맞게 요청을 보냅니다.
        const response = await fetch(URL, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                contents: [{
                    parts: [{
                        text: `당신은 해커스 교육그룹의 베테랑 교수설계자입니다. 
                        다음 정보를 분석하여 반드시 아래의 [출력 양식]에 맞춰서만 답변하세요.
                        설명이나 인사말은 생략하고 본문만 출력합니다.

                        [분석 정보]: ${input}

                        [출력 양식]:
                        ■ 강의 대주제: (강의 분야 예시: '데이터 엔지니어링'처럼 큰 주제의 명사구로 작성)
                        ■ 강의 분야: (구체적인 강의 주제 작성, 예시: 'AI 모델 성능 극대화를 위한 데이터 파이프라인 구축 및 관리')
                        ■ 제작 내용:
                        - 강의 세부 내용 1: (예시: 대용량 데이터의 수집, 저장, 가공 프로세스 자동화 시스템 설계)
                        - 강의 세부 내용 2: (예시: 고성능 검색을 위한 벡터 데이터베이스(Vector DB) 구축 및 최적화)
                        - 강의 세부 내용 3: (예시: 실시간 데이터 스트리밍 처리와 AI 학습용 데이터셋 관리 기법)`
                    }]
                }]
            })
        });

        const data = await response.json();
        
        // Gemini의 응답 텍스트 추출
        if (data.candidates && data.candidates[0].content.parts[0].text) {
            const resultText = data.candidates[0].content.parts[0].text;
            section.classList.remove('hidden');
            
            // 💡 3. 프로님이 만드신 결과 화면 디자인과 문구는 그대로 유지합니다.
            container.innerHTML = `
                <div class="bg-white p-10 rounded-2xl border border-gray-200 shadow-xl">
                    <div class="flex items-center gap-3 mb-8 border-b-2 border-indigo-500 pb-4">
                        <span class="text-2xl">📋</span>
                        <h3 class="font-bold text-xl text-gray-800 tracking-tight">강의 기획 요약 보고서</h3>
                    </div>
                    <div class="text-gray-800 font-sans leading-loose whitespace-pre-wrap text-base">
${resultText}
                    </div>
                    <div class="mt-10 pt-4 border-t border-gray-100 text-right text-xs text-gray-400 italic">
                        Generated by HRD Planning AI (Gemini)
                    </div>
                </div>`;
        }

    } catch (error) {
        console.error("연결 에러:", error);
        alert("기획안 생성 중 에러가 발생했습니다. API 키나 인터넷 연결을 확인해주세요!");
    } finally {
        btn.disabled = false;
        btn.innerText = "🚀 강의 기획안 생성하기";
    }
}

window.generatePlan = generatePlan;
